### PR TITLE
Exhaustiveness fixes

### LINKED ISSUE #461: `a := a` borks exhaustiveness checking
The following snippet:

```rust
a := 3; // value doesn't matter here
a := a;
```

Should produce this behaviour: passes exhaustiveness checking

Instead, this happened: the compiler reaches an `unreachable` part of code since `Pat::Const` is not handled.

```
compiler panics
```

### Meta

<details><summary>Backtrace</summary>
<p>

```
Sorry :^(
Internal Compiler Error: internal error: entered unreachable code

Occurred at 'compiler/hash-typecheck/src/exhaustiveness/lower.rs:117:17'
Backtrace for thread "main":
   0: backtrace::backtrace::libunwind::trace
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.65/src/backtrace/libunwind.rs:93:5
      backtrace::backtrace::trace_unsynchronized
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.65/src/backtrace/mod.rs:66:5
   1: backtrace::backtrace::trace
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.65/src/backtrace/mod.rs:53:14
   2: backtrace::capture::Backtrace::create
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.65/src/capture.rs:176:9
   3: backtrace::capture::Backtrace::new
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.65/src/capture.rs:140:22
   4: hash::crash_handler::panic_handler
             at compiler/hash/src/crash_handler.rs:40:25
   5: core::ops::function::Fn::call
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/ops/function.rs:77:5
   6: std::panicking::rust_panic_with_hook
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panicking.rs:702:17
   7: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panicking.rs:586:13
   8: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/sys_common/backtrace.rs:138:18
   9: rust_begin_unwind
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panicking.rs:584:5
  10: core::panicking::panic_fmt
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/panicking.rs:142:14
  11: core::panicking::panic
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/panicking.rs:48:5
  12: hash_typecheck::exhaustiveness::lower::LowerPatOps::deconstruct_pat
             at compiler/hash-typecheck/src/exhaustiveness/lower.rs:117:17
  13: hash_typecheck::ops::exhaustiveness::ExhaustivenessChecker::lower_pats_to_arms::{{closure}}
             at compiler/hash-typecheck/src/ops/exhaustiveness.rs:73:38
  14: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/iter/adapters/map.rs:84:28
  15: core::iter::traits::iterator::Iterator::fold
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/iter/traits/iterator.rs:2414:21
  16: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/iter/adapters/map.rs:124:9
  17: core::iter::traits::iterator::Iterator::for_each
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/iter/traits/iterator.rs:831:9
  18: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/alloc/src/vec/spec_extend.rs:40:17
  19: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  20: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/alloc/src/vec/spec_from_iter.rs:33:9
  21: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/alloc/src/vec/mod.rs:2648:9
  22: core::iter::traits::iterator::Iterator::collect
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/iter/traits/iterator.rs:1836:9
  23: itertools::Itertools::collect_vec
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.10.3/src/lib.rs:1985:9
  24: hash_typecheck::ops::exhaustiveness::ExhaustivenessChecker::lower_pats_to_arms
             at compiler/hash-typecheck/src/ops/exhaustiveness.rs:69:9
  25: hash_typecheck::ops::exhaustiveness::ExhaustivenessChecker::is_pat_irrefutable
             at compiler/hash-typecheck/src/ops/exhaustiveness.rs:112:20
  26: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_declaration
             at compiler/hash-typecheck/src/traverse/mod.rs:1591:17
  27: hash_ast::visitor::walk::walk_expr
             at compiler/hash-ast/src/visitor.rs:1472:35
  28: hash_ast::visitor::walk::walk_expr_same_children
             at compiler/hash-ast/src/visitor.rs:1584:18
  29: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_expr
             at compiler/hash-typecheck/src/traverse/mod.rs:440:9
  30: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_body_block
             at compiler/hash-typecheck/src/traverse/mod.rs:1419:32
  31: hash_ast::visitor::walk::walk_block
             at compiler/hash-ast/src/visitor.rs:2037:48
  32: hash_ast::visitor::walk::walk_block_same_children
             at compiler/hash-ast/src/visitor.rs:2060:18
  33: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_block
             at compiler/hash-typecheck/src/traverse/mod.rs:1202:9
  34: hash_ast::visitor::walk::walk_block_expr
             at compiler/hash-ast/src/visitor.rs:1780:22
  35: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_block_expr
             at compiler/hash-typecheck/src/traverse/mod.rs:695:12
  36: hash_ast::visitor::walk::walk_expr
             at compiler/hash-ast/src/visitor.rs:1499:29
  37: hash_ast::visitor::walk::walk_expr_same_children
             at compiler/hash-ast/src/visitor.rs:1584:18
  38: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_expr
             at compiler/hash-typecheck/src/traverse/mod.rs:440:9
  39: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_fn_def::{{closure}}
             at compiler/hash-typecheck/src/traverse/mod.rs:1128:31
  40: hash_typecheck::ops::scope::ScopeManager::enter_scope_with
             at compiler/hash-typecheck/src/ops/scope.rs:225:22
  41: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_fn_def
             at compiler/hash-typecheck/src/traverse/mod.rs:1127:13
  42: hash_ast::visitor::walk::walk_expr
             at compiler/hash-ast/src/visitor.rs:1516:52
  43: hash_ast::visitor::walk::walk_expr_same_children
             at compiler/hash-ast/src/visitor.rs:1584:18
  44: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_expr
             at compiler/hash-typecheck/src/traverse/mod.rs:440:9
  45: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_declaration::{{closure}}
             at compiler/hash-typecheck/src/traverse/mod.rs:1555:49
  46: core::option::Option<T>::map
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/option.rs:929:29
  47: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_declaration
             at compiler/hash-typecheck/src/traverse/mod.rs:1555:21
  48: hash_ast::visitor::walk::walk_expr
             at compiler/hash-ast/src/visitor.rs:1472:35
  49: hash_ast::visitor::walk::walk_expr_same_children
             at compiler/hash-ast/src/visitor.rs:1584:18
  50: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_expr
             at compiler/hash-typecheck/src/traverse/mod.rs:440:9
  51: hash_typecheck::traverse::scopes::<impl hash_typecheck::traverse::TcVisitor>::visit_constant_scope::{{closure}}
             at compiler/hash-typecheck/src/traverse/scopes.rs:42:17
  52: hash_typecheck::ops::scope::ScopeManager::enter_scope_with
             at compiler/hash-typecheck/src/ops/scope.rs:225:22
  53: hash_typecheck::traverse::scopes::<impl hash_typecheck::traverse::TcVisitor>::visit_constant_scope
             at compiler/hash-typecheck/src/traverse/scopes.rs:36:9
  54: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_module
             at compiler/hash-typecheck/src/traverse/mod.rs:2215:13
  55: hash_typecheck::traverse::TcVisitor::visit_source
             at compiler/hash-typecheck/src/traverse/mod.rs:96:49
  56: <hash_typecheck::TcImpl as hash_pipeline::traits::Tc>::check_module
             at compiler/hash-typecheck/src/lib.rs:116:15
  57: hash_pipeline::Compiler<P,D,S,C,V>::typecheck_source::{{closure}}
             at compiler/hash-pipeline/src/lib.rs:292:24
  58: hash_utils::timing::timed
             at compiler/hash-utils/src/timing.rs:17:9
      hash_pipeline::Compiler<P,D,S,C,V>::typecheck_source
             at compiler/hash-pipeline/src/lib.rs:291:17
  59: hash_pipeline::Compiler<P,D,S,C,V>::run_pipeline
             at compiler/hash-pipeline/src/lib.rs:364:22
  60: hash_pipeline::Compiler<P,D,S,C,V>::run
             at compiler/hash-pipeline/src/lib.rs:408:22
  61: hash_pipeline::Compiler<P,D,S,C,V>::run_on_filename
             at compiler/hash-pipeline/src/lib.rs:500:9
  62: hash::main::{{closure}}
             at compiler/hash/src/main.rs:122:17
  63: hash::execute
             at compiler/hash/src/main.rs:33:11
  64: hash::main
             at compiler/hash/src/main.rs:103:5
  65: core::ops::function::FnOnce::call_once
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/ops/function.rs:248:5
  66: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/sys_common/backtrace.rs:122:18
  67: std::rt::lang_start::{{closure}}
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/rt.rs:145:18
  68: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/ops/function.rs:280:13
      std::panicking::try::do_call
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/rt.rs:128:48
      std::panicking::try::do_call
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/rt.rs:128:20
  69: std::rt::lang_start
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/rt.rs:144:17
  70: _main

```

</p>
</details>

### LINKED ISSUE #462: exhaustiveness: unclear suggestion when checking integer ranges for exhaustiveness
The following snippet:

```rust
main := () => {
    a := 6;

    match a {
        0..20 => {};
        -50..<0 => {};
        70..127 => {};
        4..4 => {};
    }
};

```

Should produce this behaviour: should report specific integer ranges like so:

```rs
error[0083]: non-exhaustive patterns: `-2147483648i32..-51i32`, `21i32..69i32`, and `128i32..2147483647i32` not covered
 --> /Users/alex/Documents/hash-org/lang/examples/weird.hash:4:11
3 |   
4 |       match a {
  |             ^ pattern `-2147483648i32..-51i32`, `21i32..69i32`, and `128i32..2147483647i32` not covered
5 |           0..20 => {};

```

Instead, this happened: reports that `_` is missing:

```rs
error[0083]: non-exhaustive patterns: `_` not covered
 --> /Users/alex/Documents/hash-org/lang/examples/weird.hash:4:11
3 |   
4 |       match a {
  |             ^ pattern `_` not covered
5 |           0..20 => {};
```

### LINKED ISSUE #468: `or` patterns aren't being properly expanded
The exhaustiveness checking it not deal with branches that are `or` patterns properly when inserting them into the matrix.

This causes the exhaustiveness checker to panic:
```
Sorry :^(
Internal Compiler Error: trying to compare incompatible constructors Str(Str(1)) and Or

Occurred at 'compiler/hash-typecheck/src/exhaustiveness/construct.rs:278:18'
Backtrace for thread "main":
   0: backtrace::backtrace::libunwind::trace
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.65/src/backtrace/libunwind.rs:93:5
      backtrace::backtrace::trace_unsynchronized
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.65/src/backtrace/mod.rs:66:5
   1: backtrace::backtrace::trace
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.65/src/backtrace/mod.rs:53:14
   2: backtrace::capture::Backtrace::create
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.65/src/capture.rs:176:9
   3: backtrace::capture::Backtrace::new
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.65/src/capture.rs:140:22
   4: hash::crash_handler::panic_handler
             at compiler/hash/src/crash_handler.rs:40:25
   5: core::ops::function::Fn::call
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/ops/function.rs:77:5
   6: std::panicking::rust_panic_with_hook
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panicking.rs:702:17
   7: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panicking.rs:588:13
   8: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/sys_common/backtrace.rs:138:18
   9: rust_begin_unwind
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panicking.rs:584:5
  10: core::panicking::panic_fmt
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/panicking.rs:142:14
  11: hash_typecheck::exhaustiveness::construct::ConstructorOps::is_covered_by
             at compiler/hash-typecheck/src/exhaustiveness/construct.rs:278:18
  12: hash_typecheck::exhaustiveness::matrix::MatrixOps::specialise_ctor
             at compiler/hash-typecheck/src/exhaustiveness/matrix.rs:102:16
  13: hash_typecheck::exhaustiveness::usefulness::UsefulnessOps::is_useful
             at compiler/hash-typecheck/src/exhaustiveness/usefulness.rs:373:35
  14: hash_typecheck::exhaustiveness::usefulness::UsefulnessOps::compute_match_usefulness::{{closure}}
             at compiler/hash-typecheck/src/exhaustiveness/usefulness.rs:410:17
  15: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/iter/adapters/map.rs:84:28
  16: core::iter::adapters::copied::copy_fold::{{closure}}
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/iter/adapters/copied.rs:28:22
  17: core::iter::traits::iterator::Iterator::fold
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/iter/traits/iterator.rs:2414:21
  18: <core::iter::adapters::copied::Copied<I> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/iter/adapters/copied.rs:64:9
  19: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/iter/adapters/map.rs:124:9
  20: core::iter::traits::iterator::Iterator::for_each
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/iter/traits/iterator.rs:831:9
  21: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/alloc/src/vec/spec_extend.rs:40:17
  22: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  23: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/alloc/src/vec/spec_from_iter.rs:33:9
  24: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/alloc/src/vec/mod.rs:2648:9
  25: core::iter::traits::iterator::Iterator::collect
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/iter/traits/iterator.rs:1836:9
  26: hash_typecheck::exhaustiveness::usefulness::UsefulnessOps::compute_match_usefulness
             at compiler/hash-typecheck/src/exhaustiveness/usefulness.rs:405:38
  27: hash_typecheck::ops::exhaustiveness::ExhaustivenessChecker::is_match_exhaustive
             at compiler/hash-typecheck/src/ops/exhaustiveness.rs:91:22
  28: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_match_block
             at compiler/hash-typecheck/src/traverse/mod.rs:1285:17
  29: hash_ast::visitor::walk::walk_block
             at compiler/hash-ast/src/visitor.rs:2057:30
  30: hash_ast::visitor::walk::walk_block_same_children
             at compiler/hash-ast/src/visitor.rs:2088:18
  31: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_block
             at compiler/hash-typecheck/src/traverse/mod.rs:1218:9
  32: hash_ast::visitor::walk::walk_block_expr
             at compiler/hash-ast/src/visitor.rs:1808:22
  33: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_block_expr
             at compiler/hash-typecheck/src/traverse/mod.rs:711:12
  34: hash_ast::visitor::walk::walk_expr
             at compiler/hash-ast/src/visitor.rs:1513:29
  35: hash_ast::visitor::walk::walk_expr_same_children
             at compiler/hash-ast/src/visitor.rs:1598:18
  36: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_expr
             at compiler/hash-typecheck/src/traverse/mod.rs:441:9
  37: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_body_block
             at compiler/hash-typecheck/src/traverse/mod.rs:1444:31
  38: hash_ast::visitor::walk::walk_block
             at compiler/hash-ast/src/visitor.rs:2065:48
  39: hash_ast::visitor::walk::walk_block_same_children
             at compiler/hash-ast/src/visitor.rs:2088:18
  40: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_block
             at compiler/hash-typecheck/src/traverse/mod.rs:1218:9
  41: hash_ast::visitor::walk::walk_block_expr
             at compiler/hash-ast/src/visitor.rs:1808:22
  42: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_block_expr
             at compiler/hash-typecheck/src/traverse/mod.rs:711:12
  43: hash_ast::visitor::walk::walk_expr
             at compiler/hash-ast/src/visitor.rs:1513:29
  44: hash_ast::visitor::walk::walk_expr_same_children
             at compiler/hash-ast/src/visitor.rs:1598:18
  45: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_expr
             at compiler/hash-typecheck/src/traverse/mod.rs:441:9
  46: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_fn_def::{{closure}}
             at compiler/hash-typecheck/src/traverse/mod.rs:1144:31
  47: hash_typecheck::ops::scope::ScopeManager::enter_scope_with
             at compiler/hash-typecheck/src/ops/scope.rs:225:22
  48: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_fn_def
             at compiler/hash-typecheck/src/traverse/mod.rs:1143:13
  49: hash_ast::visitor::walk::walk_expr
             at compiler/hash-ast/src/visitor.rs:1530:52
  50: hash_ast::visitor::walk::walk_expr_same_children
             at compiler/hash-ast/src/visitor.rs:1598:18
  51: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_expr
             at compiler/hash-typecheck/src/traverse/mod.rs:441:9
  52: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_declaration::{{closure}}
             at compiler/hash-typecheck/src/traverse/mod.rs:1571:49
  53: core::option::Option<T>::map
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/option.rs:929:29
  54: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_declaration
             at compiler/hash-typecheck/src/traverse/mod.rs:1571:21
  55: hash_ast::visitor::walk::walk_expr
             at compiler/hash-ast/src/visitor.rs:1486:35
  56: hash_ast::visitor::walk::walk_expr_same_children
             at compiler/hash-ast/src/visitor.rs:1598:18
  57: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_expr
             at compiler/hash-typecheck/src/traverse/mod.rs:441:9
  58: hash_typecheck::traverse::scopes::<impl hash_typecheck::traverse::TcVisitor>::visit_constant_scope::{{closure}}
             at compiler/hash-typecheck/src/traverse/scopes.rs:42:17
  59: hash_typecheck::ops::scope::ScopeManager::enter_scope_with
             at compiler/hash-typecheck/src/ops/scope.rs:225:22
  60: hash_typecheck::traverse::scopes::<impl hash_typecheck::traverse::TcVisitor>::visit_constant_scope
             at compiler/hash-typecheck/src/traverse/scopes.rs:36:9
  61: <hash_typecheck::traverse::TcVisitor as hash_ast::visitor::AstVisitor>::visit_module
             at compiler/hash-typecheck/src/traverse/mod.rs:2231:13
  62: hash_typecheck::traverse::TcVisitor::visit_source
             at compiler/hash-typecheck/src/traverse/mod.rs:97:49
  63: <hash_typecheck::TcImpl as hash_pipeline::traits::Tc>::check_module
             at compiler/hash-typecheck/src/lib.rs:116:15
  64: hash_pipeline::Compiler<P,D,S,C,V>::typecheck_source::{{closure}}
             at compiler/hash-pipeline/src/lib.rs:292:24
  65: hash_utils::timing::timed
             at compiler/hash-utils/src/timing.rs:17:9
      hash_pipeline::Compiler<P,D,S,C,V>::typecheck_source
             at compiler/hash-pipeline/src/lib.rs:291:17
  66: hash_pipeline::Compiler<P,D,S,C,V>::run_pipeline
             at compiler/hash-pipeline/src/lib.rs:364:22
  67: hash_pipeline::Compiler<P,D,S,C,V>::run
             at compiler/hash-pipeline/src/lib.rs:406:22
  68: hash_pipeline::Compiler<P,D,S,C,V>::run_on_filename
             at compiler/hash-pipeline/src/lib.rs:487:9
  69: hash::main::{{closure}}
             at compiler/hash/src/main.rs:122:17
  70: hash::execute
             at compiler/hash/src/main.rs:33:11
  71: hash::main
             at compiler/hash/src/main.rs:103:5
  72: core::ops::function::FnOnce::call_once
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/ops/function.rs:248:5
  73: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/sys_common/backtrace.rs:122:18
  74: std::rt::lang_start::{{closure}}
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/rt.rs:145:18
  75: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/ops/function.rs:280:13
      std::panicking::try::do_call
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/rt.rs:128:48
      std::panicking::try::do_call
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/rt.rs:128:20
  76: std::rt::lang_start
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/rt.rs:144:17
  77: _main
```

### PR DESCRIPTION
**Pull request by feds01**
This patch fixes several issues with the exhaustiveness checking:
- `Pat::Const` should be handled as a wildcard with the given type of subject, unless the pattern itself is an enum variant which is currently not implemented. fixes #461 
- `Pat::Access` does not need to perform any special handling since the type of the pattern should already be resolved, it just needs to pass in `ty` to deconstruct_pat() recursively down until it hits `Pat::Const`
- Implement lowering `Pat::Range` into `IntRange`
- fix broken conversion logic between stored `BigInt` and `u128` representation (could be cleaned up)
- the type of the subject term should be passed into `deconstruct_pat` which fixes #462
- fixes problems with expansion of `or` patterns. fixes #468

### CODE REVIEW

File: compiler/hash-typecheck/src/exhaustiveness/lower.rs [hunk 1]
```diff
@@ -108,15 +109,22 @@ impl<'tc> LowerPatOps<'tc> {
...
             // This is essentially a simplification to some unit nominal definition like
             // for example `None`..., here we need to be able to get the `type` of the
             // actual pattern in order to figure out which
-            Pat::Access(_) | Pat::Const(_) => {
+            Pat::Const(_) => {
                 // @@EnumToUnion: when enums aren't a thing, do this with a union and create a
                 // `DeconstructedCtor::Variant(idx)` where `idx` is the union member number
-                unreachable!()
+
+                (DeconstructedCtor::Wildcard, vec![])
```
Comment (kontheocharis) [inline compiler/hash-typecheck/src/exhaustiveness/lower.rs:122]: I don't understand why this is a wildcard? it should be a constructor..

Comment (feds01) [reply compiler/hash-typecheck/src/exhaustiveness/lower.rs:122]: It depends on the type, if the underlying type is an enum variant, it's then it becomes a `DeconstructedCtor:Variant`, however in other cases `Pat::Const`as we know is used as a label for variables that have been resolved and are in scope. In the case of #461, `a` is already in scope and so becomes `Pat::Const`, but we don't care about that here and so we just treat it as a wildcard.

Comment (kontheocharis) [reply compiler/hash-typecheck/src/exhaustiveness/lower.rs:122]: Surely the constant will always point to either `Variant` or `Single`, there isn't any other valid variable that can be used in pattern position.. So why would it be a wildcard? Only binds should be treated as wildcards as I see it

Comment (feds01) [reply compiler/hash-typecheck/src/exhaustiveness/lower.rs:122]: As I explained, this doesn't happen for variables that are already in scope, so for this example:
```
a := 3;
a := a; // <--- `a` is already in scope and thus becomes a `Pat::Const`
```
Since we don't care that it is a `Pat::Const` in this particular example, we should treat it as a wildcard.

Comment (kontheocharis) [reply compiler/hash-typecheck/src/exhaustiveness/lower.rs:122]: well it just depends on the semantics of this. how do you decide if LHS is pattern matching a constructor literal or is a binding/redeclaration? like what if a was an enum variant for example, instead of 3?

Comment (feds01) [reply compiler/hash-typecheck/src/exhaustiveness/lower.rs:122]: the only other thing it could be is an enum variant that has no fields, which will then be handled when we switch to using unions

Comment (kontheocharis) [reply compiler/hash-typecheck/src/exhaustiveness/lower.rs:122]: Well, in that case what is the difference between bind and const? It seems to me that Pat::const is redundant

Comment (kontheocharis) [reply compiler/hash-typecheck/src/exhaustiveness/lower.rs:122]: Opened #469 to address this.

**Review by kontheocharis — APPROVED** [review]
